use_frameworks!

platform :ios, '8.0'

target 'JuBoManagerTest_Example' do
  pod 'JuBoManagerTest', :path => '../'

  target 'JuBoManagerTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
